apiVersion: apps/v1
kind: Deployment
metadata:
  name: sockscale-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sockscale
  template:
    metadata:
      labels:
        app: sockscale
    spec:
      containers:
        - name: sockscale
          image: mohamedselbohy/sockscale:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sockscale-service
spec:
  selector:
    app: sockscale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: socket-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sockscale-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

